[1] "Zwischenergebniss"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'rf_model_cluster.rds', probable reason 'No such file or directory'
Execution halted